#!/usr/bin/env python3
"""Single shared composition rule for the composed transaction corpus (v3).

REVIEW BLOCKER B1 — why this module exists.

In corpus v1 the five-layer precedence ladder existed as three same-author
transcriptions: ``first_gate()`` in ``build_corpus.py``, a second copy in
``verify_transactions.py``, and a ``CASE`` chain in ``oracle.sql``. The
headline "expected labels matched" could therefore only fail if one of three
transcriptions of one conjunction diverged from the others. This module is
now the ONLY Python implementation of the conjunction, of the binding stage
and of the first-rejecting-gate ladder; both ``build_corpus.py`` (which
generates the expected labels) and ``verify_transactions.py`` (which
re-derives verdicts from re-executed layer evaluators) import it.

Consequence, stated plainly and repeated in every generated summary:

    Expected labels are generated by build_corpus.py using the same
    composition rule module the verifier imports; composition-level
    agreement is analytic; the substantive check is per-layer agreement;
    labels are not externally independent.

``oracle.sql`` remains a second transcription of this ladder by design — it
is a relational RE-COMPOSITION code path over layer results and subject
strings produced by the Python evaluator, and is NOT independent validation.

BLOCKER B5 (2026-07-27) — the binding stage.
-------------------------------------------

Until v2 this function took six scalar strings (five typed layer results
plus the authority gate). No cross-layer argument existed, so no transaction
could be built in which all five layers pass individually and the
composition denies. The article's own motivating counterexample — "an
evidence receipt can correctly describe a WRITE effect when the valid
delegation path permits only READ" — was therefore ALLOWED by the shipped
composed verifier: ``evaluate_evidence`` checks only signature validity and
nonce replay, and ``required_effect`` / ``required_measurement_profile``
were inert payload bytes read by no evaluator anywhere.

v3 adds an explicit binding stage. It is NOT a sixth predicate over a sixth
artefact and it introduces no sixth verifier. It is a well-formedness
condition on the conjunction itself: the five predicates are jointly
meaningful only if they speak about the same subject. Formally

    Allow(x) = B(x) and P(x) and E(x) and S(x) and A(x) and M(x)

where B ranges over subject fields extracted from the artefacts the five
verifiers already inspect, rather than over a new artefact.

Why here and not inside a layer. ``required_effect`` is owned by the policy
artefact; ``effect`` / ``resource`` / ``issued_at`` by the evidence
artefact; the terminal narrowed scope and the delegation window by the
authority artefact; the profile identifier by the measurement artefact. A
predicate over all four has no local home. Putting it inside
``evaluate_evidence`` would make the evidence column of the 5x5 co-failure
matrix partly a copy of the policy column and could not express the
resource, time or profile mismatches at all; putting it inside the
authority evaluator would be cross-layer analysis wearing a single-layer
costume and would make the composition rule vacuous. Only the join can see
all four subjects, so only the join can reject on their disagreement.

HONESTY CEILING for the binding stage — read before citing it.

The binding stage is a deterministic string-agreement and interval-
containment condition over subject fields read out of corpus-supplied
artefacts. It verifies no signature, takes no measurement, contacts no
attestation service and proves nothing about any deployed system. It does
not make the evidence layer aware of policy, and it does not upgrade any
corpus-supplied flag into a cryptographic fact. Denials it produces are
denials on a designed corpus.

Two further properties are deliberate:

1. ``bind`` is pure over the subjects and is evaluated for EVERY
   transaction, independently of the five layer results. This is what lets
   the point-only measurement ablation keep the binding stage while
   ablating only the measurement criterion, so its historical counts are
   not silently redefined.
2. The composed ladder consults the binding result only after all five
   layers have passed. This is not fail-open: if any layer has failed the
   transaction is already DENY, and the earlier gate is the honest
   localization. When a required subject field is absent (for example a
   MISSING policy has no ``required_effect``) ``bind`` returns
   ``UNDETERMINED``, which never counts as a pass.

Deterministic by construction: pure functions over strings and lists, no
wall-clock, no randomness, no I/O.
"""

from __future__ import annotations

from typing import Any

# Exact text required by review remediation; embedded into corpus.json and
# both summary.json files so the provenance travels with the numbers.
LABEL_PROVENANCE = (
    "expected labels are generated by build_corpus.py using the same "
    "composition rule module the verifier imports; composition-level "
    "agreement is analytic; the substantive check is per-layer agreement; "
    "labels are not externally independent."
)

# Machine-readable non-claim for the binding stage, propagated into
# corpus.json, every binding details dict and both summaries.
BINDING_METHOD = (
    "deterministic string-agreement and interval-containment condition "
    "over subject fields read out of corpus-supplied artefacts; the "
    "binding stage verifies no signature, takes no measurement and is not "
    "attestation of any runtime"
)

# Fixed evaluation order of the five typed layers. The binding stage is not
# a layer and deliberately does not appear here: the 5x5 co-failure matrix
# and failed_layers stay properties of the five artefact verifiers.
EVALUATION_ORDER = ("policy", "evidence", "state", "authority", "measurement")

# Per-layer result-to-gate maps. State gates follow the appraisal order of
# state_adapter.py (contraindicated, stale, reference); oracle.sql encodes
# the same branches in the same order.
POLICY_GATES = {
    "MISSING": "policy.missing",
    "STALE": "policy.stale",
    "SUBSTITUTED": "policy.substituted",
    "INVALID_SIGNATURE": "policy.signature",
}
EVIDENCE_GATES = {
    "TAMPERED": "evidence.integrity",
    "REPLAY": "evidence.replay",
}
STATE_GATES = {
    "CONTRAINDICATED": "state.contraindicated",
    "STALE": "state.stale",
    "REFERENCE_MISMATCH": "state.reference",
}
MEASUREMENT_GATES = {
    "FAIL_POINT": "measurement.point",
    "FAIL_LCB": "measurement.confidence",
    "PROFILE_MISMATCH": "measurement.profile",
}
BINDING_GATES = {
    "EFFECT_MISMATCH": "binding.effect",
    "RESOURCE_MISMATCH": "binding.resource",
    "TIME_MISMATCH": "binding.time",
    "PROFILE_MISMATCH": "binding.measurement_profile",
    "UNDETERMINED": "binding.undetermined",
}

# Typed vocabulary of the binding stage, in rule order.
BINDING_RESULTS = (
    "UNDETERMINED",
    "EFFECT_MISMATCH",
    "RESOURCE_MISMATCH",
    "TIME_MISMATCH",
    "PROFILE_MISMATCH",
    "PASS",
)

# The two subject records of the decision transaction. These are the fields
# section 4 of the article advertises; they are real record fields, built by
# subjects_of() from the artefacts and consumed by bind().
CANONICAL_ACTION_FIELDS = (
    "effect",
    "resource",
    "operation",
    "granted_tools",
    "granted_resources",
    "authorised_from",
    "authorised_until",
    "measurement_profile",
)
OBSERVED_EFFECT_FIELDS = (
    "effect",
    "resource",
    "issued_at",
    "measurement_profile",
)


def canonical_action_of(
    policy_object: dict[str, Any] | None,
    authority_case: dict[str, Any],
) -> dict[str, Any]:
    """The action the artefacts jointly authorise.

    Sources, all read out of artefacts the five verifiers already inspect:

    - ``effect`` and ``measurement_profile`` come from the SIGNED policy
      object's ``required_effect`` / ``required_measurement_profile``. These
      two fields were inert in v1/v2 — written by the policy corpus builder,
      read by no evaluator, changing only the object digest. They are now
      load-bearing.
    - ``resource`` and ``operation`` come from the delegation case's
      terminal action.
    - ``granted_tools`` / ``granted_resources`` come from the terminal
      narrowed scope, i.e. the grant of the last delegation edge. The
      authority verifier certifies that this scope is a subset of every
      parent scope whenever it returns ALLOW, so on the transactions where
      the binding gate can decide the verdict, the scope read here is one
      the authority verifier has already validated.
    - ``authorised_from`` / ``authorised_until`` are the INTERSECTION of the
      per-edge validity windows: the interval in which the whole path is
      valid. Containment, never equality — the three decision-relevant time
      constants in this artifact (policy/state decision time
      2026-07-25T21:30:00Z, authority effect_time 2026-07-25T20:00:00Z,
      evidence issued_at 2026-07-25T21:29:30Z) are unrelated, so there is no
      single decision clock to compare against. That is a real limitation of
      the artifact and is reported, not repaired here.

    A missing policy yields ``None`` for the two policy-owned fields, which
    makes ``bind`` return ``UNDETERMINED``.
    """
    action = authority_case["action"]
    edges = authority_case["edges"]
    terminal_grant = edges[-1]["grant"]
    return {
        "effect": (
            None if policy_object is None
            else policy_object.get("required_effect")
        ),
        "resource": action.get("resource"),
        "operation": action.get("operation"),
        "granted_tools": sorted(terminal_grant.get("tools", [])),
        "granted_resources": sorted(terminal_grant.get("resources", [])),
        "authorised_from": max(edge["not_before"] for edge in edges),
        "authorised_until": min(edge["expires_at"] for edge in edges),
        "measurement_profile": (
            None if policy_object is None
            else policy_object.get("required_measurement_profile")
        ),
    }


def observed_effect_of(
    evidence_object: dict[str, Any],
    measurement_fixture: dict[str, Any],
) -> dict[str, Any]:
    """The effect as reported, plus the profile it was appraised under.

    ``effect`` / ``resource`` / ``issued_at`` are fields of the signed
    evidence object — the same object ``evaluate_evidence`` checks the
    signature of. ``measurement_profile`` is the ``profile_id`` of the
    measurement fixture whose appraisal the measurement layer executed; it
    is a corpus-supplied identifier, not a measured quantity.
    """
    return {
        "effect": evidence_object.get("effect"),
        "resource": evidence_object.get("resource"),
        "issued_at": evidence_object.get("issued_at"),
        "measurement_profile": measurement_fixture.get("profile", {}).get(
            "profile_id"
        ),
    }


def subjects_of(
    policy_object: dict[str, Any] | None,
    authority_case: dict[str, Any],
    evidence_object: dict[str, Any],
    measurement_fixture: dict[str, Any],
) -> dict[str, Any]:
    """Single derivation entry point for both subject records.

    build_corpus.py stores the result on each transaction;
    verify_transactions.py re-derives it from the re-executed inputs and
    asserts field equality (``subject_matches`` in summary.json), so the
    stored canonical_action / observed_effect are checked record fields
    rather than decoration.
    """
    return {
        "canonical_action": canonical_action_of(policy_object, authority_case),
        "observed_effect": observed_effect_of(
            evidence_object, measurement_fixture
        ),
    }


def bind(subjects: dict[str, Any]) -> dict[str, Any]:
    """Typed binding appraisal over the two subject records.

    Pure over ``subjects``; evaluated for every transaction regardless of
    the five layer results. First failing rule wins; later rules are not
    consulted.

    0. any required subject field absent  -> UNDETERMINED
    1. observed effect differs from the policy-required effect, or is not
       in the terminal granted tools           -> EFFECT_MISMATCH
    2. observed resource differs from the canonical action resource, or is
       not in the terminal granted resources   -> RESOURCE_MISMATCH
    3. issued_at outside the authorised window -> TIME_MISMATCH
    4. measurement profile differs from the policy-required profile
                                               -> PROFILE_MISMATCH
    5. otherwise                               -> PASS

    Timestamps are compared lexicographically, sound only because every
    timestamp in this artifact is fixed-width UTC ``Z`` form; both window
    boundaries are inclusive, matching state_adapter.py and the policy
    validity window in policy-version-evidence-replay/run.py.
    """
    canonical = subjects.get("canonical_action") or {}
    observed = subjects.get("observed_effect") or {}

    missing = [
        f"canonical_action.{field}"
        for field in CANONICAL_ACTION_FIELDS
        if canonical.get(field) is None
    ] + [
        f"observed_effect.{field}"
        for field in OBSERVED_EFFECT_FIELDS
        if observed.get(field) is None
    ]

    granted_tools = list(canonical.get("granted_tools") or [])
    granted_resources = list(canonical.get("granted_resources") or [])

    details: dict[str, Any] = {
        "canonical_action": dict(canonical),
        "observed_effect": dict(observed),
        "missing_subject_fields": missing,
        "effect_matches_policy": (
            observed.get("effect") == canonical.get("effect")
        ),
        "effect_within_granted_tools": observed.get("effect") in granted_tools,
        "resource_matches_canonical": (
            observed.get("resource") == canonical.get("resource")
        ),
        "resource_within_granted_resources": (
            observed.get("resource") in granted_resources
        ),
        "issued_at_within_authorised_window": (
            not missing
            and canonical["authorised_from"]
            <= observed["issued_at"]
            <= canonical["authorised_until"]
        ),
        "measurement_profile_matches_policy": (
            observed.get("measurement_profile")
            == canonical.get("measurement_profile")
        ),
        "binding_method": BINDING_METHOD,
    }

    if missing:  # rule 0
        result = "UNDETERMINED"
    elif not (
        details["effect_matches_policy"]
        and details["effect_within_granted_tools"]
    ):  # rule 1
        result = "EFFECT_MISMATCH"
    elif not (
        details["resource_matches_canonical"]
        and details["resource_within_granted_resources"]
    ):  # rule 2
        result = "RESOURCE_MISMATCH"
    elif not details["issued_at_within_authorised_window"]:  # rule 3
        result = "TIME_MISMATCH"
    elif not details["measurement_profile_matches_policy"]:  # rule 4
        result = "PROFILE_MISMATCH"
    else:  # rule 5
        result = "PASS"

    gate = "binding.verified" if result == "PASS" else BINDING_GATES[result]
    return {"result": result, "gate": gate, "details": details}


def layer_passes(layer: str, result: str) -> bool:
    """True iff the typed per-layer result counts as a pass for that layer."""
    return result == ("ALLOW" if layer == "authority" else "PASS")


def first_gate(
    policy_result: str,
    evidence_result: str,
    state_result: str,
    authority_verdict: str,
    authority_gate: str,
    measurement_result: str,
    binding_result: str,
) -> str:
    """First rejecting gate under the fixed evaluation order.

    The authority layer contributes its own evaluator-produced gate string
    (there are many authority gates); every other layer's gate is a fixed
    function of its typed result. The binding stage is last: it is reached
    only when all five artefact verifiers have passed, which is exactly the
    situation in which a denial can be attributed to the join rather than
    to any one artefact.
    """
    if policy_result != "PASS":
        return POLICY_GATES[policy_result]
    if evidence_result != "PASS":
        return EVIDENCE_GATES[evidence_result]
    if state_result != "PASS":
        return STATE_GATES[state_result]
    if authority_verdict != "ALLOW":
        return authority_gate
    if measurement_result != "PASS":
        return MEASUREMENT_GATES[measurement_result]
    if binding_result != "PASS":
        return BINDING_GATES[binding_result]
    return "verified"


def compose(
    policy_result: str,
    evidence_result: str,
    state_result: str,
    authority_verdict: str,
    authority_gate: str,
    measurement_result: str,
    subjects: dict[str, Any],
) -> dict[str, Any]:
    """Non-compensable conjunction over five typed layers AND the binding.

    Returns the full composed tuple: verdict, first rejecting gate, failed
    layers (in evaluation order), the per-layer results and the typed
    binding outcome. build_corpus.py stores this as the expected label;
    verify_transactions.py recomputes it from re-executed evaluators.
    Agreement between the two at the composition level is analytic (same
    function); only the per-layer inputs and the subject records are
    substantive.

    ``failed_layers`` deliberately stays a list over the five artefact
    layers. A transaction with ``failed_layers == []`` and
    ``verdict == "DENY"`` is therefore precisely a cross-layer denial: every
    component verifier passed and the join refused.
    """
    layer_results = {
        "policy": policy_result,
        "evidence": evidence_result,
        "state": state_result,
        "authority": authority_verdict,
        "measurement": measurement_result,
    }
    failed_layers = [
        layer
        for layer in EVALUATION_ORDER
        if not layer_passes(layer, layer_results[layer])
    ]
    binding = bind(subjects)
    return {
        "verdict": (
            "ALLOW"
            if not failed_layers and binding["result"] == "PASS"
            else "DENY"
        ),
        "first_rejecting_gate": first_gate(
            policy_result,
            evidence_result,
            state_result,
            authority_verdict,
            authority_gate,
            measurement_result,
            binding["result"],
        ),
        "failed_layers": failed_layers,
        "layer_results": layer_results,
        "binding_result": binding["result"],
        "binding_gate": binding["gate"],
    }
