#!/usr/bin/env python3
"""Deterministic artifact-manifest generator for the research-factory packets.

Walks the packet directory that contains this script and emits
``artifact-manifest.md``: one SHA-256 row per source-of-record file, ordered by
relative path, preceded by package-scale bullets.

Determinism contract
--------------------
* No wall-clock, no randomness, no network, no environment reads.
* The output depends only on (a) the bytes of the packet on disk and (b) the
  constants in this file.
* Running it twice on an unchanged tree produces byte-identical output.
* The generated date is a constant below, not ``today``. Bump it deliberately.

Scope
-----
Hash rows cover every non-scratch regular file in the packet, regardless of
suffix: documentation, executable sources, corpora, result streams, rendered
figures, nested checksum files, build inputs, logs, and PDFs. Per-directory
``SHA256SUMS`` files remain convenient local integrity records, while this
manifest closes the complete packet tree.

Excluded entirely — neither hashed nor counted — is machine scratch
(``__pycache__``, ``*.pyc``, editor swap files, VCS and tool caches) and the
manifest itself, which cannot contain its own hash.

Usage
-----
    python3 make_manifest.py            # writes ./artifact-manifest.md
    python3 make_manifest.py --check    # recompute and diff, write nothing
"""

from __future__ import annotations

import argparse
import hashlib
import sys
from pathlib import Path

# --- constants (the only non-filesystem inputs) ------------------------------

GENERATED_DATE = "2026-07-28"

MANIFEST_NAME = "artifact-manifest.md"

# Directories that are machine scratch, never packet content.
EXCLUDED_DIR_NAMES = frozenset(
    {
        "__pycache__",
        ".git",
        ".hg",
        ".svn",
        ".ipynb_checkpoints",
        ".pytest_cache",
        ".mypy_cache",
        ".ruff_cache",
        ".tox",
        ".venv",
        "scratch",
        ".scratch",
    }
)

# File suffixes that are machine scratch.
EXCLUDED_SUFFIXES = frozenset({".pyc", ".pyo", ".pyd", ".swp", ".swo", ".orig", ".rej"})

# Exact file names that are machine scratch.
EXCLUDED_NAMES = frozenset({".DS_Store", "Thumbs.db", "desktop.ini"})

STATUS_LINE = (
    "Internal research-factory packet. No submission, upload, deposit, DOI, "
    "public release, or repository push is authorized."
)

# Head note per packet, keyed by the packet directory name, so that the same
# generator file can be copied between packets and still regenerate the right
# document with no arguments.
HEAD_NOTES = {
    "research-factory-v3-2026-07-25": (
        "Regenerated 2026-07-27. The 2026-07-25 manifest under-counted the packet "
        "and its size figure was wrong; the packet also gained checksum and "
        "repair-note files from the documented provenance packaging repair. "
        "Generated by `make_manifest.py` — never hand-edited."
    ),
    "research-factory-v4-2026-07-27": (
        "Regenerated 2026-07-28 for the r5 flagship, corpus-wide native-state "
        "overlay plus compiled verifier, finite model check, process and "
        "five-container durable revocation, separate SQL and blind semantic "
        "audit paths, release preparation, updated portable source capsule, "
        "and JAIR internal prototype. Generated by "
        "`make_manifest.py` — never hand-edited."
    ),
}

DEFAULT_HEAD_NOTE = "Generated by `make_manifest.py` — never hand-edited."


# --- walking -----------------------------------------------------------------


def is_excluded(path: Path, root: Path) -> bool:
    """True if *path* is machine scratch."""
    rel = path.relative_to(root)
    if any(part in EXCLUDED_DIR_NAMES for part in rel.parts[:-1]):
        return True
    if path.name in EXCLUDED_NAMES:
        return True
    if path.suffix in EXCLUDED_SUFFIXES:
        return True
    return False


def collect(root: Path) -> tuple[list[Path], list[Path], list[Path]]:
    """Return (included, hashed, excluded) file lists, each sorted by path.

    ``included`` is every packet file that is not machine scratch.
    ``hashed`` is the subset that gets a hash row.
    ``excluded`` is the scratch that was skipped, reported for transparency.

    The manifest at ``root/MANIFEST_NAME`` is dropped from all three lists. It
    cannot carry its own hash, and counting it anywhere would make the output
    depend on whether a previous manifest happened to exist — the first
    generation and every regeneration must produce identical bytes.
    """
    included: list[Path] = []
    excluded: list[Path] = []
    manifest = root / MANIFEST_NAME
    for path in root.rglob("*"):
        if path.is_symlink() or not path.is_file():
            continue
        if path == manifest:
            continue
        if is_excluded(path, root):
            excluded.append(path)
        else:
            included.append(path)

    def key(p: Path) -> str:
        return p.relative_to(root).as_posix()

    included.sort(key=key)
    excluded.sort(key=key)
    hashed = list(included)
    return included, hashed, excluded


def sha256_of(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


# --- rendering ---------------------------------------------------------------


def kind_of(path: Path) -> str:
    """A stable, human-readable kind label used in the breakdown bullets."""
    if path.suffix:
        return path.suffix.lstrip(".")
    return path.name


def kind_histogram(paths: list[Path]) -> list[tuple[str, int, int]]:
    """[(kind, count, bytes)] ordered by descending count then kind name."""
    counts: dict[str, list[int]] = {}
    for path in paths:
        entry = counts.setdefault(kind_of(path), [0, 0])
        entry[0] += 1
        entry[1] += path.stat().st_size
    rows = [(kind, c, b) for kind, (c, b) in counts.items()]
    rows.sort(key=lambda row: (-row[1], row[0]))
    return rows


def render(root: Path) -> str:
    included, hashed, excluded = collect(root)
    unhashed: list[Path] = []

    total_bytes = sum(p.stat().st_size for p in included)
    hashed_bytes = sum(p.stat().st_size for p in hashed)
    head_note = HEAD_NOTES.get(root.name, DEFAULT_HEAD_NOTE)

    lines: list[str] = []
    add = lines.append

    add("# Artifact manifest")
    add("")
    add(f"Packet: `{root.name}`  ")
    add(f"Generated: {GENERATED_DATE}  ")
    add(f"Status: {STATUS_LINE}")
    add("")
    add(f"> {head_note}")
    add("")
    add("## Package scale")
    add("")
    add(
        f"- **{len(included)} files** in the packet, excluding machine scratch "
        f"and this manifest."
    )
    add(
        f"- **{total_bytes:,} bytes** total — "
        f"**{total_bytes / 1048576:.2f} MiB** (binary, 1 MiB = 1,048,576 B) = "
        f"**{total_bytes / 1000000:.2f} MB** (decimal, 1 MB = 1,000,000 B). "
        f"Both units are given because the two conventions differ by about 5% "
        f"at this scale and the earlier manifest was ambiguous about which it "
        f"used."
    )
    add(
        f"- **{len(hashed)} files carry a hash row below** "
        f"({hashed_bytes:,} bytes = {hashed_bytes / 1048576:.2f} MiB = "
        f"{hashed_bytes / 1000000:.2f} MB): every non-scratch regular file "
        "in the packet."
    )
    add(
        f"- **{len(unhashed)} files are counted but not hashed here**: "
        + (
            ", ".join(f"{count} `{kind}`" for kind, count, _ in kind_histogram(unhashed))
            if unhashed
            else "none"
        )
        + "."
    )
    add(
        f"- **{len(excluded)} scratch files excluded** from both the count and "
        "the hash rows: "
        + (
            ", ".join(f"{count} `{kind}`" for kind, count, _ in kind_histogram(excluded))
            if excluded
            else "none"
        )
        + ". This manifest is also excluded, because it cannot contain its own hash."
    )
    add("")
    add("Hashed files by kind:")
    add("")
    add("| Kind | Files | Bytes |")
    add("| --- | ---: | ---: |")
    for kind, count, size in kind_histogram(hashed):
        add(f"| `.{kind}` | {count} | {size:,} |")
    add("")
    add("## Hash rows")
    add("")
    add(
        "SHA-256 over file bytes, ordered by relative path (byte order of the "
        "POSIX relative path). Recompute with:"
    )
    add("")
    add("```bash")
    add(f"cd {root.name}")
    add("sha256sum <relative-path>")
    add("```")
    add("")
    add("| SHA-256 | Bytes | Artifact |")
    add("| --- | ---: | --- |")
    for path in hashed:
        rel = path.relative_to(root).as_posix()
        add(f"| `{sha256_of(path)}` | {path.stat().st_size:,} | `{rel}` |")
    add("")

    return "\n".join(lines) + "\n"


# --- entry point -------------------------------------------------------------


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--root",
        type=Path,
        default=None,
        help="packet root (default: the directory containing this script)",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="recompute and compare against the manifest on disk; write nothing",
    )
    args = parser.parse_args(argv)

    root = (args.root or Path(__file__).resolve().parent).resolve()
    if not root.is_dir():
        print(f"FAIL: not a directory: {root}", file=sys.stderr)
        return 2

    text = render(root)
    out = root / MANIFEST_NAME

    if args.check:
        if not out.exists():
            print(f"FAIL: {out} does not exist", file=sys.stderr)
            return 1
        current = out.read_text(encoding="utf-8")
        if current == text:
            print(f"OK: {out} is current")
            return 0
        print(f"FAIL: {out} differs from a fresh generation", file=sys.stderr)
        return 1

    out.write_text(text, encoding="utf-8")
    included, hashed, excluded = collect(root)
    total_bytes = sum(p.stat().st_size for p in included)
    print(f"wrote {out}")
    print(
        f"  {len(included)} files, {total_bytes:,} bytes "
        f"({total_bytes / 1048576:.2f} MiB = {total_bytes / 1000000:.2f} MB)"
    )
    print(f"  {len(hashed)} hash rows, {len(excluded)} scratch files excluded")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
